USE QUANLYBANHANG_TEST
GO
-- I/ Cau 11
---             Them     Xoa          Sua
---HOADON         +       -      +(NGHD, MAKH)
---KHACHHANG      -       -      +(MAKH, NGDK)

CREATE TRIGGER TRG_INSERT_UPDATE_HD_NGHD_NGDK ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT * FROM INSERTED, KHACHHANG
		WHERE (INSERTED.MAKH = KHACHHANG.MAKH) AND NGHD < NGDK
	)
	BEGIN
		PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA HOA DON THANH CONG'
	END
END

GO

CREATE TRIGGER TRG_UPDATE_KH_NGHD_NGDK ON KHACHHANG
FOR UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT * FROM INSERTED, HOADON
		WHERE (INSERTED.MAKH = HOADON.MAKH) AND NGHD < NGDK
	)
	BEGIN
		PRINT 'LOI: NGAY DANG KY THANH VIEN KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUA KHACH HANG THANH CONG'
	END
END

GO
-- I/ Cau 12
---             Them     Xoa          Sua
---HOADON         +       -      +(NGHD, MANV)
---NHANVIEN       -       -      +(MANV, NGVL)

CREATE TRIGGER TRG_INSERT_UPDATE_NV_NGHD_NGVL ON NHANVIEN
FOR UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT * FROM INSERTED, HOADON
		WHERE (INSERTED.MANV = HOADON.MANV) AND NGHD < NGVL
	)
	BEGIN
		PRINT 'LOI: NGAY VAO LAM CUA NHAN VIEN KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUA NHAN VIEN THANH CONG'
	END
END

GO

CREATE TRIGGER TRG_INSERT_UPDATE_HD_NGHD_NGVL ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(
		SELECT * FROM INSERTED, NHANVIEN
		WHERE (INSERTED.MANV = NHANVIEN.MANV) AND NGHD < NGVL
	)
	BEGIN
		PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA HOA DON THANH CONG'
	END
END

GO
-- I/ Cau 13. Trị giá của một hóa đơn là tổng thành tiền (số lượng*đơn giá) của các chi tiết thuộc hóa đơn đó
---             Them     Xoa          Sua
---CTHD          +        +       +(SOHD, SL, MASP)
---HOADON        +        -       +(SOHD, TRIGIA)
---SANPHAM       -        -       +(MASP, GIA)

CREATE TRIGGER TRG_UPDATE_CTHD_TRIGIA ON CTHD
FOR UPDATE 
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = TRIGIA 
	+ (
		SELECT SUM(SL*GIA)
		FROM INSERTED I
			JOIN SANPHAM SP ON SP.MASP = I.MASP
		WHERE I.SOHD = HOADON.SOHD
	)
	- (
		SELECT SUM(SL*GIA)
		FROM DELETED D
			JOIN SANPHAM SP ON SP.MASP = D.MASP
		WHERE D.SOHD = HOADON.SOHD
	)
	PRINT('DA CAP NHAT GIA TRI HOADON')
END

GO

CREATE TRIGGER TRG_INSERT_CTHD_TRIGIA ON CTHD
FOR INSERT
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = TRIGIA 
	+ (
		SELECT SUM(SL*GIA)
		FROM INSERTED I
			JOIN SANPHAM SP ON SP.MASP = I.MASP
		WHERE I.SOHD = HOADON.SOHD
	)
	PRINT('DA CAP NHAT GIA TRI HOADON')
END

GO

CREATE TRIGGER TRG_DELETE_CTHD_TRIGIA ON CTHD
FOR DELETE
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = TRIGIA 
	- (
		SELECT SUM(SL*GIA)
		FROM DELETED D
			JOIN SANPHAM SP ON SP.MASP = D.MASP
		WHERE D.SOHD = HOADON.SOHD
	)
	PRINT('DA CAP NHAT GIA TRI HOADON')
END

GO

CREATE TRIGGER TRG_INSERT_HD_TRIGIA ON HOADON
FOR INSERT
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = 0
	FROM HOADON HD JOIN INSERTED I ON HD.SOHD = I.SOHD
	PRINT 'DA CAP NHAT TRIGIA BAN DAU=0'
END

GO

CREATE TRIGGER TRG_UPDATE_HD_TRIGIA ON HOADON
FOR UPDATE
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = (
		SELECT SUM(SL*GIA)
		FROM CTHD JOIN SANPHAM SP ON CTHD.MASP = SP.MASP
		WHERE I.SOHD = HD.SOHD
	)
	FROM HOADON HD
		JOIN INSERTED I ON HD.SOHD = I.SOHD
	PRINT('DA CAP NHAT TRI GIA HOA DON')
END

GO

CREATE TRIGGER TRG_UPDATE_HD_TRIGIA_SP_GIA ON SANPHAM
FOR UPDATE
AS
BEGIN
	UPDATE HOADON
	SET TRIGIA = KQ.TRIGIA
	FROM HOADON HD,
		(	SELECT SOHD, SUM(SL * GIA) AS TRIGIA
			FROM CTHD CT
				JOIN SANPHAM SP ON CT.MASP = SP.MASP
			GROUP BY SOHD
		) AS KQ
	WHERE HD.SOHD = KQ.SOHD
	PRINT 'DA CAP NHAT TRI GIA HOA DON'
END

GO


-- I/ Cau 14. Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua.
---             Them     Xoa          Sua
---HOADON         +       +     +(MAKH, TRIGIA)
---KHACHHANG      +       -     +(MAKH, DOANHSO)

CREATE TRIGGER TRG_UPDATE_HOADON_DOANHSO ON HOADON
FOR UPDATE
AS
BEGIN
	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO
	+ ( SELECT I.TRIGIA
		FROM INSERTED I JOIN KHACHHANG KH ON I.MAKH=KH.MAKH
	  )
	- (	SELECT D.TRIGIA
		FROM DELETED D JOIN KHACHHANG KH ON D.MAKH=KH.MAKH
	  )
	PRINT 'DA CAP NHAT DOANH SO KHACH HANG'
END

GO

CREATE TRIGGER TRG_INSERT_HOADON_DOANHSO ON HOADON
FOR INSERT
AS
BEGIN
	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO
	+ ( SELECT I.TRIGIA
		FROM INSERTED I JOIN KHACHHANG KH ON I.MAKH=KH.MAKH
	  )
	PRINT 'DA CAP NHAT DOANH SO KHACH HANG'
END

GO

CREATE TRIGGER TRG_DELETE_HOADON_DOANHSO ON HOADON
FOR DELETE
AS
BEGIN
	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO
	- ( SELECT D.TRIGIA
		FROM DELETED D JOIN KHACHHANG KH ON D.MAKH=KH.MAKH
	  )
	PRINT 'DA CAP NHAT DOANH SO KHACH HANG'
END
GO

CREATE TRIGGER TRG_INSERT_KH_DOANHSO ON KHACHHANG
FOR INSERT
AS
BEGIN
	UPDATE KHACHHANG
	SET DOANHSO = 0
	FROM KHACHHANG KH JOIN INSERTED I ON I.MAKH=KH.MAKH
	PRINT 'DA CAP NHAT DOANH SO BAN DAU = 0'
END

GO

CREATE TRIGGER TRG_UPDATE_KH_DOANHSO ON KHACHHANG
FOR UPDATE
AS
BEGIN
	 IF EXISTS (
		SELECT * FROM INSERTED I,
			(SELECT MAKH, SUM(TRIGIA) AS DOANHSO
			FROM HOADON
			WHERE MAKH IS NOT NULL
			GROUP BY MAKH) AS KQ
		WHERE I.MAKH = KQ.MAKH AND I.DOANHSO <> KQ.DOANHSO
	 )
	 BEGIN
		PRINT ' CAP NHAT DOANH SO SAI '
		ROLLBACK TRANSACTION
	 END
END
GO



