USE QUANLYGIAOVU

-- 19.
SELECT TOP 1 with ties MAKHOA, TENKHOA
FROM KHOA
ORDER BY NGTLAP

-- 20.
SELECT HOCHAM, COUNT(HOCHAM) SL FROM GIAOVIEN 
WHERE HOCHAM IN ('GS', 'PGS') 
GROUP BY HOCHAM

-- 21.
SELECT KH.MAKHOA, KH.TENKHOA, GV.HOCVI, COUNT(GV.HOCVI) SL
FROM GIAOVIEN GV JOIN KHOA KH ON GV.MAKHOA = KH.MAKHOA  
WHERE GV.HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS' ) 
GROUP BY KH.MAKHOA, KH.TENKHOA, GV.HOCVI
ORDER BY MAKHOA DESC

-- 22.
SELECT MH.MAMH, MH.TENMH, KQT.KQUA, COUNT(KQT.MAHV) SL
FROM MONHOC MH JOIN (
	SELECT K1.MAHV, K1.MAMH, K1.LANTHI, K1.KQUA
	FROM KETQUATHI K1
	LEFT JOIN KETQUATHI K2 ON K1.MAHV = K2.MAHV AND K1.MAMH = K2.MAMH AND K1.LANTHI < K2.LANTHI
	WHERE K2.MAHV IS NULL
) AS KQT
ON MH.MAMH = KQT.MAMH
GROUP BY MH.MAMH, MH.TENMH, KQT.KQUA
ORDER BY MH.MAMH

-- 23.
SELECT MAGV, HOTEN 
FROM GIAOVIEN 
WHERE MAGV IN(
	SELECT DISTINCT MAGV
	FROM GIANGDAY GD JOIN LOP
	ON GD.MALOP = LOP.MALOP
	WHERE MAGV = MAGVCN 
)

-- 24.
SELECT HO + ' ' + TEN HOTEN, LOP.MALOP
FROM LOP JOIN HOCVIEN HV
ON LOP.TRGLOP = HV.MAHV
WHERE SISO = (
	SELECT MAX(SISO) FROM LOP
)

-- 25.
SELECT HO + ' ' + TEN HOTEN FROM HOCVIEN
WHERE MAHV IN (
	SELECT MAHV FROM KETQUATHI A
	WHERE MAHV IN (
		SELECT TRGLOP FROM LOP
	) AND NOT EXISTS (
		SELECT 1 FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND KQUA = 'Khong Dat'
	GROUP BY MAHV
	HAVING COUNT(MAMH) >= 3
)

-- 26.
SELECT MAHV, HO + ' ' + TEN HOTEN FROM HOCVIEN
WHERE MAHV IN(
	SELECT TOP 1 with ties HV.MAHV FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV=KQT.MAHV
	WHERE KQT.DIEM BETWEEN 9 AND 10
	GROUP BY HV.MAHV
	ORDER BY COUNT(HV.MAHV) DESC
)

-- 27.
SELECT LEFT(A.MAHV, 3) MALOP, A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, RANK () OVER (PARTITION BY LEFT(KQ.MAHV, 3) ORDER BY COUNT(MAMH) DESC) RANK_MH FROM KETQUATHI KQ 
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY KQ.MAHV
) A JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
WHERE RANK_MH = 1
GROUP BY LEFT(A.MAHV, 3), A.MAHV, HO, TEN

-- 28.
SELECT HOCKY, NAM, MAGV, COUNT(MAMH) SOMH, COUNT(MALOP) SOLOP FROM GIANGDAY
GROUP BY HOCKY, NAM, MAGV

-- 29.
SELECT HOCKY, NAM, GV.MAGV, HOTEN FROM (
	SELECT HOCKY, NAM, MAGV, RANK() OVER (PARTITION BY HOCKY, NAM ORDER BY COUNT(MAMH) DESC) RANK_SOMH FROM GIANGDAY
	GROUP BY HOCKY, NAM, MAGV
) TEMP_GV JOIN GIAOVIEN GV 
ON TEMP_GV.MAGV = GV.MAGV
WHERE RANK_SOMH = 1

-- 30.
SELECT MH.MAMH,MH.TENMH FROM (
	SELECT MAMH, RANK () OVER(ORDER BY COUNT(MAHV) DESC) RANK_MH_KD FROM KETQUATHI
	WHERE LANTHI=1 AND KQUA = 'Khong Dat'
	GROUP BY MAMH
	) TEMP_MH JOIN MONHOC MH 
ON TEMP_MH.MAMH=MH.MAMH
WHERE RANK_MH_KD=1

-- 31.
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SOLANDAT FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) A JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV

-- 32.
SELECT TEMP_HV.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT A.MAHV, COUNT(A.KQUA) SOLANDAT FROM KETQUATHI A
	WHERE(
		NOT EXISTS (
		SELECT 1 FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
		) 
		AND A.KQUA = 'Dat'	
	)
	GROUP BY A.MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) TEMP_HV JOIN HOCVIEN HV
ON TEMP_HV.MAHV = HV.MAHV

-- 33.
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SOLANDAT FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) A JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV

-- 34.
SELECT TEMP_HV.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT A.MAHV, COUNT(A.KQUA) SOLANDAT FROM KETQUATHI A
	WHERE(
		NOT EXISTS (
		SELECT 1 FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI< B.LANTHI
		) 
		AND A.KQUA = 'Dat'	
	)
	GROUP BY A.MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERELANTHI= 1
	GROUP BY MAHV
) TEMP_HV JOIN HOCVIEN HV
ON TEMP_HV.MAHV = HV.MAHV

-- 35.
SELECT A.MAHV, HO + ' ' + TEN HOTEN, A.MAMH, A.DIEM_MAX FROM (
	SELECT B.MAMH, MAHV, DIEM, DIEM_MAX
	FROM KETQUATHI B JOIN (
		SELECT MAMH, MAX(DIEM) DIEM_MAX FROM KETQUATHI
		GROUP BY MAMH
	) C 
	ON B.MAMH = C.MAMH
	WHERE NOT EXISTS (
		SELECT 1 FROM KETQUATHI D 
		WHERE B.MAHV = D.MAHV AND B.MAMH = D.MAMH AND B.LANTHI< D.LANTHI
	) AND DIEM = DIEM_MAX
) A JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV