USE QUANLYGIAOVU

---					PHẦN III
--- Câu 19. Khoa nào (mã khoa, tên khoa) được thành lập sớm nhất.
SELECT TOP 1 WITH TIES MAKHOA, TENKHOA, NGTLAP
FROM KHOA
GROUP BY MAKHOA, TENKHOA, NGTLAP
ORDER BY NGTLAP ASC;

--- Câu 20. Có bao nhiêu giáo viên có học hàm là “GS” hoặc “PGS”.
SELECT HOCHAM, COUNT (MAGV) AS SOGIAOVIEN
FROM GIAOVIEN
WHERE HOCHAM IN ('PGS', 'GS')
GROUP BY HOCHAM;

--- Câu 21.	Thống kê có bao nhiêu giáo viên có học vị là “CN”, “KS”, “Ths”, “TS”, “PTS” trong mỗi khoa.
SELECT K.TENKHOA, K.MAKHOA, GV.HOCVI, COUNT (GV.MAGV) AS SOGIAOVIEN
FROM KHOA K
	JOIN GIAOVIEN GV ON K.MAKHOA = GV.MAKHOA
WHERE GV.HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS')
GROUP BY K.TENKHOA, K.MAKHOA, GV.HOCVI
ORDER BY K.TENKHOA, GV.HOCVI ASC;

--- Câu 22.	Mỗi môn học thống kê số lượng học viên theo kết quả (đạt và không đạt).
SELECT MH.TENMH, MH.MAMH, KQT.KQUA, COUNT (KQT.MAHV) AS SOHOCVIEN
FROM MONHOC MH 
	JOIN KETQUATHI KQT ON MH.MAMH = KQT.MAMH
GROUP BY MH.TENMH, MH.MAMH, KQT.KQUA
ORDER BY MH.TENMH, KQT.KQUA ASC;

--- Câu 23.	Tìm giáo viên (mã giáo viên, họ tên) là giáo viên chủ nhiệm của một lớp, đồng thời dạy cho lớp đó ít nhất một môn học.
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
	JOIN LOP L ON GV.MAGV = L.MAGVCN
	JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV AND L.MALOP = GD.MALOP;

--- Câu 24.	Tìm họ tên lớp trưởng của lớp có sỉ số cao nhất.
SELECT TOP 1 WITH TIES HV.HO + ' ' + HV.TEN AS HOTEN_TRGLP, L.MALOP, L.SISO
FROM HOCVIEN HV
	JOIN LOP L ON HV.MAHV = L.TRGLOP
GROUP BY HV.HO, HV.TEN, L.MALOP, L.SISO
ORDER BY L.SISO DESC;

--- Câu 25. Tìm họ tên những LOPTRG thi không đạt quá 3 môn (mỗi môn đều thi không đạt ở tất cả các lần thi).
SELECT HO + ' ' + TEN AS HOTEN_TRGLP
FROM HOCVIEN
WHERE MAHV IN
(
	SELECT MAHV 
	FROM KETQUATHI KQT_A
	WHERE MAHV IN (SELECT TRGLOP FROM LOP)
		AND NOT EXISTS (SELECT 1 FROM KETQUATHI KQT_B WHERE KQT_A.MAMH = KQT_B.MAMH AND KQT_A.MAHV = KQT_B.MAHV AND KQT_A.LANTHI < KQT_B.LANTHI)
		AND KQT_A.KQUA = 'Khong Dat'
	GROUP BY MAHV
	HAVING COUNT(KQT_A.MAMH) >= 3
)

--- Câu 26. Tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
--			Cách 1
SELECT TOP 1 WITH TIES KQT.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN,COUNT (KQT.MAMH) AS SOMONHOC_9_10
FROM KETQUATHI KQT
	JOIN HOCVIEN HV ON KQT.MAHV = HV.MAHV
WHERE KQT.DIEM BETWEEN 9 AND 10
GROUP BY KQT.MAHV, HV.HO, HV.TEN
ORDER BY SOMONHOC_9_10 DESC;

--			Cách 2
SELECT HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, SOMONHOC_9_10
FROM 
(
	SELECT HV.MAHV, HV.HO, HV.TEN, COUNT(KQT.MAMH) AS  SOMONHOC_9_10, RANK () OVER (ORDER BY COUNT(KQT.MAMH) DESC) RANK_MH
	FROM KETQUATHI KQT 
		JOIN HOCVIEN HV ON KQT.MAHV = HV.MAHV
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY HV.MAHV, HV.HO,HV.TEN
) HV
	JOIN KETQUATHI KQT ON KQT.MAHV = HV.MAHV
WHERE RANK_MH = 1
GROUP BY HV.MAHV, HV.HO, HV.TEN, SOMONHOC_9_10;

--- Câu 27.	Trong từng lớp, tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9, 10 nhiều nhất.
SELECT  HV.MALOP, HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, SOMONHOC_9_10
FROM 
(
	SELECT HV.MAHV, HV.MALOP, HV.HO, HV.TEN, COUNT(KQT.MAMH) AS  SOMONHOC_9_10, RANK () OVER (PARTITION BY HV.MALOP ORDER BY COUNT(KQT.MAMH) DESC) RANK_MH
	FROM KETQUATHI KQT 
		JOIN HOCVIEN HV ON KQT.MAHV = HV.MAHV
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY HV.MAHV, HV.MALOP, HV.HO,HV.TEN
) HV
	JOIN KETQUATHI KQT ON KQT.MAHV = HV.MAHV
WHERE RANK_MH = 1
GROUP BY HV.MALOP, HV.MAHV, HV.HO, HV.TEN, SOMONHOC_9_10;

--- Câu 28. Trong từng học kỳ của từng năm, mỗi giáo viên phân công dạy bao nhiêu môn học, bao nhiêu lớp.
SELECT HOCKY, NAM, MAGV, COUNT(MAMH) AS SOMH, COUNT(MALOP) AS SOLOP 
FROM GIANGDAY
GROUP BY HOCKY, NAM, MAGV

--- Câu 29. Trong từng học kỳ của từng năm, tìm giáo viên (mã giáo viên, họ tên) giảng dạy nhiều nhất.
SELECT GD.HOCKY, GD.NAM, GD.MAGV, GV.HOTEN, GD.SOMONDAY
FROM 
(
	SELECT MAGV, HOCKY, NAM, COUNT(MAMH) AS SOMONDAY, RANK () OVER (PARTITION BY HOCKY, NAM ORDER BY COUNT(MAMH) DESC) RANK_GD
	FROM GIANGDAY
	GROUP BY MAGV, HOCKY, NAM
) GD
	JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE RANK_GD = 1
ORDER BY NAM ASC;

--- Câu 30. Tìm môn học (mã môn học, tên môn học) có nhiều học viên thi không đạt (ở lần thi thứ 1) nhất.
SELECT	MH.MAMH, MH.TENMH, THI.SOHV_KO_DAT_LAN1
FROM 
(
	SELECT MAMH, COUNT (MAHV) AS SOHV_KO_DAT_LAN1, RANK () OVER (ORDER BY COUNT (MAHV) DESC) RANK_HV
	FROM KETQUATHI
	WHERE LANTHI = 1 AND KQUA = 'Khong Dat'
	GROUP BY MAMH
) THI
	JOIN MONHOC MH ON MH.MAMH = THI.MAMH
WHERE RANK_HV = 1;

--- Câu 31. Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi thứ 1).
WITH SO_MON_THI AS
(
	SELECT MAHV, COUNT(MAMH) AS SOMH 
	FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
)

SELECT DAT.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN 
FROM 
(
	SELECT KQT.MAHV, SMT.SOMH
	FROM KETQUATHI KQT
		JOIN SO_MON_THI SMT ON KQT.MAHV = SMT.MAHV
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY KQT.MAHV, SMT.SOMH
	HAVING COUNT(KQUA) = SMT.SOMH
) DAT
	JOIN HOCVIEN HV
ON DAT.MAHV = HV.MAHV

--- Câu 32. Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi sau cùng).
WITH SO_MON_THI AS
(
	SELECT MAHV, COUNT(MAMH) AS SOMH 
	FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
)

SELECT DAT.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN 
FROM 
(
	SELECT KQT.MAHV, SMT.SOMH
	FROM KETQUATHI KQT
		JOIN SO_MON_THI SMT ON KQT.MAHV = SMT.MAHV
	WHERE LANTHI <= SMT.SOMH AND KQUA = 'Dat'
	GROUP BY KQT.MAHV, SMT.SOMH
	HAVING COUNT(KQUA) = SMT.SOMH
) DAT
	JOIN HOCVIEN HV
ON DAT.MAHV = HV.MAHV

--- Câu 33. Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi thứ 1).
WITH SO_MON_THI AS
(
	SELECT MAHV, COUNT(MAMH) AS SOMH 
	FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
)

SELECT DAT.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN 
FROM 
(
	SELECT KQT.MAHV, SMT.SOMH
	FROM KETQUATHI KQT
		JOIN SO_MON_THI SMT ON KQT.MAHV = SMT.MAHV
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY KQT.MAHV, SMT.SOMH
	HAVING COUNT(KQUA) = SMT.SOMH
) DAT
	JOIN HOCVIEN HV
ON DAT.MAHV = HV.MAHV

--- Câu 34. Tìm học viên (mã học viên, họ tên) đã thi tất cả các môn và đều đạt (chỉ xét lần thi sau cùng).
WITH SO_MON_THI AS
(
	SELECT MAHV, COUNT(MAMH) AS SOMH 
	FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
)

SELECT DAT.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN 
FROM 
(
	SELECT KQT.MAHV, SMT.SOMH
	FROM KETQUATHI KQT
		JOIN SO_MON_THI SMT ON KQT.MAHV = SMT.MAHV
	WHERE LANTHI <= SMT.SOMH AND KQUA = 'Dat'
	GROUP BY KQT.MAHV, SMT.SOMH
	HAVING COUNT(KQUA) = SMT.SOMH
) DAT
	JOIN HOCVIEN HV
ON DAT.MAHV = HV.MAHV

--- Câu 35. Tìm học viên (mã học viên, họ tên) có điểm thi cao nhất trong từng môn (lấy điểm ở lần thi sau cùng).
SELECT KQT.MAMH, HV.MAHV, HV.HO + ' ' + HV.TEN AS HOTEN, DIEM_MAX.DIEMCAONHAT
FROM HOCVIEN HV 
	JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
	JOIN 
	(
		SELECT MAMH, MAX(DIEM) AS DIEMCAONHAT
		FROM KETQUATHI
		GROUP BY MAMH
	) DIEM_MAX ON KQT.MAMH = DIEM_MAX.MAMH AND KQT.DIEM = DIEM_MAX.DIEMCAONHAT
WHERE NOT EXISTS (SELECT 1 FROM KETQUATHI KQT_B WHERE KQT.MAMH = KQT_B.MAMH AND KQT.MAHV = KQT_B.MAHV AND KQT.LANTHI < KQT_B.LANTHI)
