--- Câu 1. Có bao nhiêu sản phẩm khác nhau được bán ra trong năm 2020.
SELECT COUNT(DISTINCT CTHD.MASP) AS SOLGSP _2020
FROM CTHD
	JOIN HOADON HD ON CTHD.MAHD = HD.MAHD
WHERE YEAR(HD.NGAYHD) = 2020;

--- Câu 2. Cho biết trị giá hóa đơn cao nhất, thấp nhất là bao nhiêu?
SELECT MAX(TRIGIA) AS TRIGIACAONHAT, MIN(TRIGIA) AS TRIGIATHAPNHAT
FROM HOADON;

--- Câu 3. Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2020 là bao nhiêu?
SELECT AVG(TRIGIA) AS TRIGIATRUNGBINH_2020
FROM HOADON
WHERE YEAR(NGHD) = 2020;

--- Câu 4. Tính doanh thu bán hàng trong năm 2020.
SELECT SUM(TRIGIA) AS TONGDOANHTHU_2020
FROM HOADON
WHERE YEAR(NGHD) = 2020;

--- Câu 5. Tìm số hóa đơn có trị giá cao nhất trong năm 2020.
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2020 AND TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE NGHD = 2020);

--- Cách 2
SELECT TOP 1 WITH TIES SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2020
ORDER BY TRIGIA DESC;

--- Câu 6. Tìm họ tên khách hàng đã mua hóa đơn có trị giá cao nhất trong năm 2020.
SELECT KH.HOTEN
FROM KHACHHANG KH
	JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE HD.TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) = 2020) AND HD.NGHD = 2020;

--- Cách 2
SELECT TOP 1 WITH TIES KH HOTEN
FROM KHACHHANG KH
	JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE YEAR(NGHD) = 2020
ORDER BY TRIGIA DESC;

--- Câu 7. Tính tổng số sản phẩm do “Viet Nam” sản xuất.
SELECT COUNT(MASP) AS TONGSPVIETNAM
FROM SANPHAM
WHERE NUOCSX = 'Viet Nam';

--- Câu 8. Tính tổng số sản phẩm của từng nước sản xuất.
SELECT NUOCSX, COUNT(MASP) AS SOLGSPTHEONUOC
FROM SANPHAM
GROUP BY NUOCSX;

--- Câu 9.Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm.
SELECT NUOCSX, MAX(GIA) AS GIACAONHAT, MIN(GIA) AS GIATHAPNHAT, AVG(GIA) AS GIATRUNGBINH
FROM SANPHAM
GROUP BY NUOCSX;

--- Câu 10. Tính doanh thu bán hàng mỗi ngày.
SELECT NGHD, SUM(TRIGIA) AS DOANHTHUTHEONGAY
FROM HOADON
GROUP BY NGHD;

--- Câu 11. Tính tổng số lượng bán ra của từng sản phẩm trong tháng 10/2020.
SELECT CTHD.MASP, SUM(CTHD.SL) AS TONGSOLG_10/2020
FROM CTHD
	JOIN HOADON HD ON CTHD.SOHD = HD.SOHD
WHERE MONTH(HD.NGHD) = 10 AND YEAR(HD.NGHD) = 2020
GROUP BY CTHD.MASP;

--- Câu 12. Tính doanh thu bán hàng của từng tháng trong năm 2020.
SELECT MONTH(NGHD) AS THANG, SUM(TRGIA) AS DOANHTHUTHEOTHANG
FROM HOADON
WHERE YEAR(NGHD) = 2020
GROUP BY MONTH(NGHD);

--- Câu 13. Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4;

--- Câu 14. In ra danh sách 3 khách hàng (MAKH, HOTEN) có doanh số cao nhất.
SELECT KH.MAKH, KH.HOTEN, SUM(HD.TRIGIA) AS DOANHSO
FROM KHACHHANG KH
	JOIN HOADON HD ON KH.MAKH = HD.MAKH
GROUP BY KH.MAKH, KH.HOTEN
ORDER BY DOANHSO DESC
LIMIT 3;

--- Câu 15. In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng 1 trong 3 mức giá cao nhất.
SELECT MASP, TENSP
FROM SANPHAM
WHERE GIA IN (SELECT DISTINCT GIA FROM SANPHAM ORDER BY GIA DESC LIMIT 3);

--- Câu 16. In ra danh sách các sản phẩm (MASP, TENSP) do “Thai Lan” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của tất cả các sản phẩm).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan' AND GIA IN (SELECT DISTINCT GIA FROM SANPHAM ORDER BY GIA DESC LIMIT 3);

--- Câu 17. In ra danh sách các sản phẩm (MASP, TENSP) do “Viet Nam” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của sản phẩm do “Viet Nam” sản xuất).
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Viet Nam' AND GIA IN (SELECT DISTINCT GIA FROM SANPHAM WHERE NUOCSX = 'Viet Nam' ORDER BY GIA DESC LIMIT 3);

--- Câu 18. Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT SOHD
FROM CTHD
WHERE MASP IN (SELECT MASP FROM SANPHAM WHERE NUOCSX = 'Viet Nam')
GROUP BY SOHD
HAVING COUNT (DISTINCT MASP) = 3;

--- Câu 19. Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất. 
SELECT KH.MAKH, KH.HOTEN, COUNT(HD.SOHD) AS SOLANMUA
FROM KHACHHANG KH
	JOIN HOADON HD ON KH.MAKH = HD.MAKH
GROUP BY KH.MAKH, KH.HOTEN
ORDER BY SOLANMUA DESC
LIMIT 1;

---  Câu 20.Tháng mấy trong năm 2020, doanh số bán hàng cao nhất ?
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHSO
FROM HOADON
WHERE YEAR(NGHD) = 2020
GROUP BY THANG
ORDER BY DOANHSO DESC
LIMIT 1;

--- Câu 21. Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2020.
SELECT SP.MASP, SP.TENSP, SUM(CTHD.SL) AS TONGSL_2020
FROM SANPHAM 
	RIGHT JOIN CTHD ON SP.MASP = CTHD.MASP
	JOIN HOADON HD ON CTHD.SOHD = HD.SOHD
WHERE YEAR(HD.NGHD) = 2020
GROUP BY SP.MASP, SP.TENSP
ORDER BY TONGSL_2020 ASC
LIMIT 1;

--- Câu 22. Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;

--- Câu 23. Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
WITH GIACAONHATMOINUOC AS 
(
    SELECT NUOCSX, MAX(GIA) AS GIACAONHAT
    FROM SANPHAM
    GROUP BY NUOCSX
)

SELECT SP.MASP, SP.TENSP, SP.NUOCSX, SP.GIA
FROM SANPHAM SP
	JOIN GIACAONHATMOINUOC GCN ON SP.NUOCSX = GCN.NUOCSX AND SP.GIA = GCN.GIACAONHAT;

--- Câu 24. In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng mức giá cao thứ hai.
SELECT MASP, TENSP, GIA
FROM SANPHAM
WHERE GIA IN (SELECT DISTINCT GIA FROM SANPHAM ORDER BY GIA DESC LIMIT 1 OFFSET 1);

--- Câu 25. In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng mức giá cao thứ hai và thứ ba.SELECT MASP, TENSP, GIA
FROM SANPHAM
WHERE GIA IN (SELECT DISTINCT GIA FROM SANPHAM ORDER BY GIA DESC LIMIT 2 OFFSET 1);

--- Câu 26. Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
WITH TOPCUSTOMERS AS
(
	SELECT KH.MAKH, KH.HOTEN, SUM(HD.TRIGIA) AS DOANHSO
	FROM KHACHHANG KH
		JOIN HOADON HD ON KH.MAKH = HD.MAKH
	GROUP BY KH.MAKH, KH.HOTEN
	ORDER BY DOANHSO DESC
	LIMIT 10
)

SELECT TC.MAKH, TC.HOTEN, COUNT(HD.SOHD) AS SOLANMUA
FROM TOPCUSTOMERS TC
	JOIN HOADON HD ON TC.MAKH = HD.MAKH
GROUP BY TC.MAKH, TC.HOTEN
ORDER BY SOLANMUA DESC
LIMIT 1;

--- Câu 27. Tìm sản phẩm (MASP, TENSP) bán chạy nhất theo từng tháng.
WITH SOLUONGBAN AS
(
	SELECT MONTH(HD.NGHD) AS THANG, SP.MASP, SP.TENSP, COUNT(CTHD.SOHD) AS SOLANBAN
	FROM CTHD	
		JOIN SANPHAM SP ON CTHD.MASP = SP.MASP
		JOIN HOADON HD ON CTHD.SOHD = HD.SOHD
	WHERE YEAR(HD.NGHD) = 2020
	GROUP BY THANG, SP.MASP, SP.TENSP
)

WITH MAXSOLG AS
(
	SELECT THANG, MAX(SOLANBAN) AS BANCHAYNHAT
	FROM SOLUONGBAN
	GROUP BY THANG
)

SELECT SOLUONGBAN.THANG, SOLUONGBAN.MASP, SOLUONGBAN.TENSP, MAXSOLG.BANCHAYNHAT
FROM SOLUONGBAN	
	JOIN MAXSOLG ON SOLUONGBAN.THANG = MAXSOLG.THANG AND SOLUONGBAN.SOLANBAN = MAXSOLG.BANCHAYNHAT
GROUP BY SOLUONGBAN.THANG
ORDER BY SOLUONGBAN.THANG;

--- Câu 28. In ra danh sách 3 khách hàng có doanh số cao nhất (sắp xếp theo kiểu xếp hạng).
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, SUM(HOADON.TRIGIA) AS DOANHSO
FROM KHACHHANG
	JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY DOANHSO DESC
LIMIT 3;
