CREATE DATABASE QUANLYGIAOVU

USE QUANLYGIAOVU

--- C헧 1
CREATE TABLE HOCVIEN
(
    MAHV char(5) NOT NULL,
    HO varchar(40),
	TEN varchar(10),
    NGSINH smalldatetime,
	GIOITINH varchar(3),
    NOISINH varchar(40),
    MALOP char(3),
    CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV)
)

CREATE TABLE LOP
(
	MALOP char(3) NOT NULL,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
)

CREATE TABLE KHOA 
(
	MAKHOA varchar(4) NOT NULL,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA	char(4),
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)

CREATE TABLE MONHOC
(
	MAMH varchar(10) NOT NULL,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4),
	CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH)
)

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10) NOT NULL,
	MAMH_TRUOC varchar(10),
	CONSTRAINT PK_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN
(
	MAGV char(4) NOT NULL,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)

CREATE TABLE GIANGDAY
(
	MALOP char(3) NOT NULL,
	MAMH varchar(10) NOT NULL,
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH)
)

CREATE TABLE KETQUATHI
(
	MAHV char(5) NOT NULL,
	MAMH varchar(10) NOT NULL,
	LANTHI tinyint NOT NULL,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10)
	CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV, MAMH, LANTHI)
)

ALTER TABLE HOCVIEN ADD
GHICHU varchar(20),
DIEMTB numeric(4,2),
XEPLOAI varchar(10),
CONSTRAINT FK_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE LOP ADD 
CONSTRAINT FK_LOP_GVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV),
CONSTRAINT FK_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE MONHOC 
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA) 

ALTER TABLE GIANGDAY ADD
CONSTRAINT FK_GIANGDAY_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV), 
CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN 
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE KETQUATHI ADD 
CONSTRAINT FK_KQUA_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
CONSTRAINT FK_KQUA_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN ADD
CONSTRAINT FK_DK_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
CONSTRAINT FK_DK_MONHOC_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
GO

--- C헧 2
CREATE FUNCTION check_phantruoc_MAHV (@MAHV varchar(5))
RETURNS TINYINT
AS
BEGIN
	IF LEFT(@MAHV, 3) IN (SELECT MALOP FROM LOP)
		RETURN 1
	RETURN 0
END
GO

CREATE FUNCTION check_phansau_MAHV (@MAHV varchar(5), @MALOP_HOCVIEN varchar(3))
RETURNS TINYINT
AS
BEGIN
    IF RIGHT(@MAHV, 2) BETWEEN 1 AND (SELECT SISO FROM LOP WHERE MALOP = @MALOP_HOCVIEN)
		RETURN 1
	RETURN 0
END
GO

ALTER TABLE HOCVIEN ADD 
CONSTRAINT CK_MAHV CHECK(LEN(MAHV) = 5 AND dbo.check_phantruoc_MAHV(MAHV) = 1 AND dbo.check_phansau_MAHV(MAHV, MALOP) = 1),
CONSTRAINT CHECK_GIOITINH CHECK (GIOITINH IN ('Nam', 'Nu')) --- C헧 3

ALTER TABLE KETQUATHI ADD
CONSTRAINT CHECK_DIEM CHECK (DIEM BETWEEN 1 AND 10 AND (LEN(SUBSTRING(CAST(DIEM AS VARCHAR), CHARINDEX('.', DIEM) + 1, 1000)) >= 2)), --- C헧 4
CONSTRAINT CHECK_LANTHI CHECK (LANTHI BETWEEN 0 AND 3), --- C헧 6
CONSTRAINT CK_KQUA CHECK(KQUA = CASE WHEN (DIEM BETWEEN 5 AND 10) THEN 'Dat' ELSE 'Khong dat' END) --- C헧 5

--- C헧 7
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHECK_HOCKKY CHECK (HOCKY BETWEEN 1 AND 3)

--- C헧 8
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT CHECK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))
GO

