CREATE DATABASE QUANLYBANHANG

USE QUANLYBANHANG
CREATE TABLE KHACHHANG
(
    MAKH char(4) NOT NULL,
    HOTEN varchar(40),
    DCHI varchar(50),
    SODT varchar(20),
    NGSINH smalldatetime,
    NGDK smalldatetime,
    DOANHSO money,
    CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE NHANVIEN
(
    MANV char(4) NOT NULL,
    HOTEN varchar(40),
    SODT varchar(20),
    NGVL smalldatetime,
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE SANPHAM
(
    MASP char(4) NOT NULL,
    TENSP varchar(40),
    DVT varchar(20),
    NUOCSX varchar(40),
    GIA money,
    CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)

CREATE TABLE HOADON
(
    SOHD int NOT NULL,
    NGHD smalldatetime,
    MAKH char(4),
    MANV char(4),
    TRIGIA money,
    CONSTRAINT PK_HOADON PRIMARY KEY (SOHD)
)

CREATE TABLE CTHD
(
    SOHD int NOT NULL,
    MASP char(4) NOT NULL,
    SL int,
    CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
)

ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE SANPHAM
ADD GHICHU varchar(20)

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100)

ALTER TABLE SANPHAM
DROP COLUMN GHICHU

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH varchar(20)

ALTER TABLE SANPHAM
ADD CONSTRAINT CHECK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

ALTER TABLE SANPHAM
ADD CONSTRAINT CHECK_GIA CHECK (GIA > 500)

ALTER TABLE CTHD
ADD CONSTRAINT CHECK_SL CHECK (SL > 0)

ALTER TABLE KHACHHANG
ADD CONSTRAINT CHECK_NG CHECK (NGDK > NGSINH)
