--- Câu 1. Tạo database tên BAITHI gồm có 4 table NHAPHANPHOI, MYPHAM, PHIEUNHAP, CTPN. Tạo khóa chính, khóa ngoại cho các table đó.

CREATE DATABASE BAITHI

USE BAITHI

SET DATEFORMAT DMY

CREATE TABLE NHAPHANPHOI 
(
	MANPP CHAR(5) PRIMARY KEY,
	TENNPP VARCHAR(40),
	QUOCGIA VARCHAR(20),
	LOAINPP VARCHAR(20)
)

CREATE TABLE MYPHAM
(
	MAMP CHAR(4) PRIMARY KEY,
	TENMP VARCHAR(40),
	LOAIMP VARCHAR(30),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP
(
	SOPN INT PRIMARY KEY, 
	MANPP CHAR(5) REFERENCES NHAPHANPHOI,
	NGNHAP SMALLDATETIME,
	LOAINHAP VARCHAR(20)
)

CREATE TABLE CTPN
(
	SOPN INT REFERENCES PHIEUNHAP,
	MAMP CHAR(4) REFERENCES MYPHAM,
	SOLUONG INT, 
	PRIMARY KEY(SOPN, MAMP)
)

--- Câu 2. Nhập dữ liệu cho 4 table như đề bài.

--- NHAPHANPHOI
INSERT INTO NHAPHANPHOI(MANPP, TENNPP, QUOCGIA, LOAINPP) VALUES
('NPP01', 'Cocoon', 'Viet Nam', 'Thuong xuyen'),
('NPP02', 'Canmake', 'Nhat Ban ', 'Vang lai'),
('NPP03', 'Estee Lauder', 'Hoa Ky ', 'Vang lai');

--- MYPHAM
INSERT INTO MYPHAM(MAMP, TENMP, LOAIMP, GIA) VALUES
('MP01', 'Sua rua mat', 'Dung dich', 200000),
('MP02', 'Son duong moi', 'Son', 25000),
('MP03', 'Mascara', 'Gel', 330000);

--- PHIEUNHAP
INSERT INTO PHIEUNHAP (SOPN, MANPP, NGNHAP, LOAINHAP) VALUES
(2301, 'NPP01', '22/11/2023', 'Noi dia'),
(2302, 'NPP03', '04/12/2023', 'Nhap khau'),
(2303, 'NPP02', '10/12/2023', 'Nhap khau');

--- CTPN
INSERT INTO CTPN (SOPN, MAMP, SOLUONG) VALUES
(2301, 'MP01', 123),
(2301, 'MP02', 234),
(2303, 'MP03', 345);

--- Câu 3. Thực hiện ràng buộc toàn vẹn sau: Tất cả các mỹ phẩm dạng Gel đều có giá lớn hơn 100.000.

ALTER TABLE MYPHAM ADD CONSTRAINT CK_GIA_GEL CHECK (NOT(LOAIMP = 'Gel' AND GIA <= 100000))

--- Câu 4.Thực hiện ràng buộc toàn vẹn sau: Phiếu nhập của những nhà phân phối ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu.

--- Bảng tầm ảnh hưởng
---					Thêm	Xóa		Sửa
--- NHAPHANPHOI		  -		 -	  +(QUOCGIA)
--- PHIEUNHAP		  +		 -	  +(LOAINHAP,MANPP)

GO
CREATE TRIGGER TRG_UPD_NHAPHANPHOI ON NHAPHANPHOI 
FOR UPDATE
AS IF UPDATE(QUOCGIA)
BEGIN
	IF EXISTS 
	(
		SELECT I.MANPP 
		FROM INSERTED I, PHIEUNHAP PN
		WHERE I.MANPP = PN.MANPP AND I.QUOCGIA <> 'Việt Nam' AND PN.LOAINHAP <> 'Nhap khau'
	)				
	BEGIN
		PRINT('LOI: QUOC GIA KHONG HOP LE')
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT('CAP NHAT NHA PHAN PHOI THANH CONG')
	END
END

GO
CREATE TRIGGER TRG_INS_UPD_PHIEUNHAP ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS 
	(
		SELECT I.MANPP 
		FROM INSERTED I, NHAPHANPHOI NPP
		WHERE I.MANPP = NPP.MANPP AND NPP.QUOCGIA <> 'Việt Nam' AND I.LOAINHAP <> 'Nhap khau'
	)
	BEGIN 
		PRINT('LOI: LOAI NHAP HOAC MA NHA PHAN PHOI KHONG HOP LE')
		ROLLBACK TRAN
	END
	ELSE 
	BEGIN
		PRINT('THEM/CAP NHAT NHA PHAN PHOI THANH CONG')
	END
END

--- Câu 5. Tìm tất cả các phiếu nhập có ngày nhập trong tháng 12 năm 2023, sắp xếp kết quả tăng dần theo ngày nhập.
SELECT *
FROM PHIEUNHAP
WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2023
ORDER BY NGNHAP ASC;

--- Câu 6. Tìm mỹ phẩm được nhập số lượng nhiều nhất trong năm 2023.
SELECT TOP 1 WITH TIES CTPN.MAMP, MP.TENMP, SUM(CTPN.SOLUONG) AS TONGSOLUONGNHAP
FROM CTPN 
	JOIN PHIEUNHAP PN ON CTPN.SOPN = PN.SOPN
	JOIN MYPHAM MP ON CTPN.MAMP = MP.MAMP
WHERE YEAR(PN.NGNHAP) = 2023
GROUP BY CTPN.MAMP, MP.TENMP
ORDER BY TONGSOLUONGNHAP DESC;

--- Câu 7.Tìm mỹ phẩm chỉ có nhà phân phối thường xuyên cung cấp, nhà phân phối vãng lai không cung cấp.
SELECT MP.MAMP, MP.TENMP
FROM CTPN 
	JOIN PHIEUNHAP PN ON CTPN.SOPN = PN.SOPN
	JOIN NHAPHANPHOI NPP ON PN.MANPP = NPP.MANPP
	JOIN MYPHAM MP ON CTPN.MAMP = MP.MAMP
WHERE NPP.LOAINPP = 'Thuong xuyen'
EXCEPT
SELECT MP.MAMP, MP.TENMP 
FROM CTPN 
	JOIN PHIEUNHAP PN ON CTPN.SOPN = PN.SOPN
	JOIN NHAPHANPHOI NPP ON PN.MANPP = NPP.MANPP
	JOIN MYPHAM MP ON CTPN.MAMP = MP.MAMP
WHERE NPP.LOAINPP = 'Vang lai'

--- Câu 8. Tìm nhà phân phối đã từng cung cấp tất cả những mỹ phẩm có giá trên 200.000 trong năm 2023.
SELECT *
FROM NHAPHANPHOI NPP
WHERE NOT EXISTS 
(
	SELECT *
	FROM MYPHAM MP
	WHERE MP.GIA > 200000 AND NOT EXISTS 
	(
		SELECT *
		FROM PHIEUNHAP PN 
			JOIN CTPN ON CTPN.SOPN = PN.SOPN
		WHERE PN.MANPP = NPP.MANPP AND CTPN.MAMP = MP.MAMP AND YEAR(PN.NGNHAP) = 2023
	)
)

